# Site settings
title: Dinesh Pandian
email: dinesh.may23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a UI/UX Designer and Developer based in India. I have an obsession with making things pixel perfect.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dineshux.in" # the base hostname & protocol for your site
twitter_username: dineshux
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

